version: "3.8"

services:
  protekauto-cms:
    env_file:
      - stack.env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BEELINE_SMS_USER=${BEELINE_SMS_USER}
        - BEELINE_SMS_PASS=${BEELINE_SMS_PASS}
        - BEELINE_SMS_SENDER=${BEELINE_SMS_SENDER}
        - DATABASE_URL=${DATABASE_URL}
        - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
        - JWT_SECRET=${JWT_SECRET}
        - AWS_REGION=${AWS_REGION}
        - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
        - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
        - AWS_S3_BUCKET=${AWS_S3_BUCKET}
        - S3_ENDPOINT=${S3_ENDPOINT}
        - NEXTAUTH_URL=${NEXTAUTH_URL}
        - LAXIMO_LOGIN=${LAXIMO_LOGIN}
        - LAXIMO_PASSWORD=${LAXIMO_PASSWORD}
        - LAXIMO_DOC_LOGIN=${LAXIMO_DOC_LOGIN}
        - LAXIMO_DOC_PASSWORD=${LAXIMO_DOC_PASSWORD}
        - YOOKASSA_SHOP_ID=${YOOKASSA_SHOP_ID}
        - YOOKASSA_SECRET_KEY=${YOOKASSA_SECRET_KEY}
        - AUTOEURO_API_KEY=${AUTOEURO_API_KEY}
        # PartsAPI/PartsIndex removed
        - YANDEX_MAPS_API_KEY=${YANDEX_MAPS_API_KEY}
        - YANDEX_DELIVERY_TOKEN=${YANDEX_DELIVERY_TOKEN}
        - YANDEX_GEOSUGGEST_API_KEY=${YANDEX_GEOSUGGEST_API_KEY}
        - YANDEX_DELIVERY_SOURCE_STATION_ID=${YANDEX_DELIVERY_SOURCE_STATION_ID}
        - CMS_PORT=${CMS_PORT}
        - NEXT_PUBLIC_FRONTEND_ORIGIN=${NEXT_PUBLIC_FRONTEND_ORIGIN}
    ports:
      - "${CMS_PORT:-3000}:3000"
    environment:
      # Порт приложения
      - CMS_PORT=${CMS_PORT:-3000}

      # База данных (внешняя)
      - DATABASE_URL=${DATABASE_URL}

      # NextAuth и JWT
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - JWT_SECRET=${JWT_SECRET}

      # AWS S3 для файлов
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}

      # URL для доступа к админке
      - NEXTAUTH_URL=${NEXTAUTH_URL}

      # SMS API Билайн
      - BEELINE_SMS_USER=${BEELINE_SMS_USER}
      - BEELINE_SMS_PASS=${BEELINE_SMS_PASS}
      - BEELINE_SMS_SENDER=${BEELINE_SMS_SENDER}

      # Laximo API
      - LAXIMO_LOGIN=${LAXIMO_LOGIN}
      - LAXIMO_PASSWORD=${LAXIMO_PASSWORD}
      - LAXIMO_DOC_LOGIN=${LAXIMO_DOC_LOGIN}
      - LAXIMO_DOC_PASSWORD=${LAXIMO_DOC_PASSWORD}

      # YooKassa платежи
      - YOOKASSA_SHOP_ID=${YOOKASSA_SHOP_ID}
      - YOOKASSA_SECRET_KEY=${YOOKASSA_SECRET_KEY}

      # AutoEuro API
      - AUTOEURO_API_KEY=${AUTOEURO_API_KEY}

      # PartsAPI ключи
      # PartsAPI removed

      # PartsIndex API
      # PartsIndex removed

      # Яндекс API ключи
      - YANDEX_MAPS_API_KEY=${YANDEX_MAPS_API_KEY}
      - YANDEX_DELIVERY_TOKEN=${YANDEX_DELIVERY_TOKEN}
      - YANDEX_GEOSUGGEST_API_KEY=${YANDEX_GEOSUGGEST_API_KEY}
      - YANDEX_DELIVERY_SOURCE_STATION_ID=${YANDEX_DELIVERY_SOURCE_STATION_ID}

      # S3 дополнительные настройки
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
      - S3_ENDPOINT=${S3_ENDPOINT}

      # Ozon API
      - OZON_CLIENT_ID=${OZON_CLIENT_ID}
      - OZON_API_KEY=${OZON_API_KEY}
      - OZON_MOCK=${OZON_MOCK}

      # OpenAI (AI Chat)
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL}

      # DaData API
      - DADATA_API_KEY=${DADATA_API_KEY}

      # ZZAP (опционально, скриншоты)
      - ZZAP_EMAIL=${ZZAP_EMAIL}
      - ZZAP_PASSWORD=${ZZAP_PASSWORD}

      # Публичный origin фронтенда (используется в клиентском коде)
      - NEXT_PUBLIC_FRONTEND_ORIGIN=${NEXT_PUBLIC_FRONTEND_ORIGIN}

      # Окружение
      - NODE_ENV=production

    restart: unless-stopped
